%--------------------------------------------------------------------------
function fieldNames = clusterFieldsByDim(dim)
    % field names of S_clu storing per-cluster values, by dimension

    if dim < 1 || dim > 3
        error('bad dimension: %d', dim);
    end

    clusterFieldNames = {
        {'clusterSites', ... % 1-dimensional fields
         'nSpikesPerCluster', ...
         'clusterXPositions', ...
         'clusterYPositions', ...
         'vrVmin_clu', ...
         'viSite_min_clu', ...
         'vrVpp_clu', ...
         'vrSnr_clu', ...
         'vnSite_clu', ...
         'vnSpk_clu', ...
         'vrIsoDist_clu', ...
         'vrLRatio_clu', ...
         'vrIsiRatio_clu', ...
         'vrVpp_uv_clu', ...
         'vrVmin_uv_clu', ...
         'clusterCenters', ...
         'clusterNotes', ... % cell
         'spikesByCluster'}, % cell
        {'mrWavCor'}, % 2-dimensional fields
        {'trWav_spk_clu', ... % 3-dimensional fields
         'tmrWav_spk_clu', ...
         'trWav_raw_clu', ...
         'tmrWav_raw_clu', ...
         'tmrWav_clu', ...
         'tmrWav_raw_lo_clu', ...
         'tmrWav_raw_hi_clu'}
    };

    fieldNames = clusterFieldNames{dim};
end
