function hFigWav = plotFigWav(hFigWav, hClust, hCfg, maxAmp)
    %PLOTFIGWAV Plot the main view (FigWav)
    if ~hFigWav.hasAxes('default') % construct from scratch
        hFigWav.addAxes('default');
        hFigWav.axApply('default', @set, 'Position', [.05 .05 .9 .9], 'XLimMode', 'manual', 'YLimMode', 'manual');
        hFigWav.axApply('default', @xlabel, 'Cluster #');
        hFigWav.axApply('default', @ylabel, 'Site #');
        hFigWav.axApply('default', @grid, 'on');

        % hFigWav.figData.vcTitle = 'Scale: %0.1f uV; [H]elp; [Left/Right]:Select cluster; (Sft)[Up/Down]:scale; [M]erge; [S]plit auto; [D]elete; [A]:Resample spikes; [P]STH; [Z]oom; in[F]o; [Space]:Find similar [0]:Annotate Delete [1]:Annotate Signle [2]:Annotate Multi'; % TW
        % hFigWav.axApply('default', @title, sprintf('Scale: %0.1f uV; [H]elp; [Left/Right]:Select cluster; (Sft)[Up/Down]:scale; [M]erge; [S]plit auto; [D]elete; [A]:Resample spikes; [P]STH; [Z]oom; in[F]o; [Space]:Find similar [0]:Annotate Delete [1]:Annotate Signle [2]:Annotate Multi', maxAmp));
        
        hFigWav.axApply('default', @axis, [0, hClust.nClusters + 1, 0, hCfg.nSites + 1]);
        hFigWav = plotSpikeWaveforms(hFigWav, hClust, hCfg, maxAmp);
        hFigWav = plotMeanWaveforms(hFigWav, hClust, hCfg, maxAmp);
        hFigWav.setHideOnDrag('hSpkAll');
    else
        hFigWav = plotSpikeWaveforms(hFigWav, hClust, hCfg, maxAmp);
        % clear mean waveforms
        iGroup = 1;
        while hFigWav.hasPlot(sprintf('Group%d', iGroup))
            hFigWav.rmPlot(sprintf('Group%d', iGroup));
            iGroup = iGroup + 1;
        end
        % replot mean waveforms
        hFigWav = plotMeanWaveforms(hFigWav, hClust, hCfg, maxAmp);
    end

    info_ = jrclust.utils.info();
    hFigWav.axApply('default', @title, sprintf('%s v%s; press [H] for help (scale: %0.1f uV)', info_.program, jrclust.utils.version(), maxAmp));

    hFigWav.figData.helpText = {'[Left-click] Select unit', ...
                                '[Right-click] Select secondary unit', ...
                                '[Shift-click or wheel click, drag]: Pan', ...
                                '[Mouse wheel] Zoom in/out', ...
                                '[X + Wheel] X-zoom select', ...
                                '[Y + Wheel] Y-zoom select', ...
                                '[(Shift) Up]: Increase amplitude scale', ...
                                '[(Shift) Down]: Decrease amplitude scale', ...
                                '[(Shift) Right]: Select next cluster (as secondary if shift)', ...
                                '[(Shift) Left]: Select previous cluster (as secondary if shift', ...
                                '[Home]: Select first cluster', ...
                                '[End]: Select last cluster', ...
                                '[Space] Select next most similar unit', ...
                                '------------------', ...
                                '[0] Mark selected unit for deletion', ...
                                '[1] Annotate selected unit as single', ...
                                '[2] Annotate selected unit as MUA', ...
                                '------------------', ...
                                '[A] Resample spikes', ...
                                '[D] Delete selected unit', ...
                                '[G] Go to a specific unit', ...
                                '[H] Help', ...
                                '[M] Merge selected units', ...
                                '[N] Toggle spike count in X labels', ...
                                '[P] Display PSTH plot'...
                                '[Q] Show quality scores for selected unit', ...
                                '[R] Reset view', ...
                                '[S] Split unit', ...
                                '[W] Toggle spike traces', ...
                                '[Z] Zoom in on selected unit'};
end
