function hFigWav = doPlotFigWav(hFigWav, hClust, hCfg, maxAmp)
    %DOPLOTFIGWAV Plot the main view (FigWav)
    if ~hFigWav.hasAxes('default') % construct from scratch
        hFigWav.addAxes('default');
        hFigWav.axApply('default', @set, 'Position', [.05 .05 .9 .9], 'XLimMode', 'manual', 'YLimMode', 'manual');
        hFigWav.axApply('default', @xlabel, 'Cluster #');
        hFigWav.axApply('default', @ylabel, 'Site #');
        hFigWav.axApply('default', @grid, 'on');

        % hFigWav.figData.vcTitle = 'Scale: %0.1f uV; [H]elp; [Left/Right]:Select cluster; (Sft)[Up/Down]:scale; [M]erge; [S]plit auto; [D]elete; [A]:Resample spikes; [P]STH; [Z]oom; in[F]o; [Space]:Find similar [0]:Annotate Delete [1]:Annotate Signle [2]:Annotate Multi'; % TW
        % hFigWav.axApply('default', @title, sprintf('Scale: %0.1f uV; [H]elp; [Left/Right]:Select cluster; (Sft)[Up/Down]:scale; [M]erge; [S]plit auto; [D]elete; [A]:Resample spikes; [P]STH; [Z]oom; in[F]o; [Space]:Find similar [0]:Annotate Delete [1]:Annotate Signle [2]:Annotate Multi', maxAmp));
        
        hFigWav.axApply('default', @axis, [0, hClust.nClusters + 1, 0, hCfg.nSites + 1]);
        hFigWav = plotSpikeWaveforms(hFigWav, hClust, hCfg, maxAmp);
        hFigWav = plotMeanWaveforms(hFigWav, hClust, hCfg, maxAmp);
        hFigWav.setHideOnDrag('hSpkAll');
    else
        hFigWav = plotSpikeWaveforms(hFigWav, hClust, hCfg, maxAmp);
        % clear mean waveforms
        iGroup = 1;
        while hFigWav.hasPlot(sprintf('Group%d', iGroup))
            hFigWav.rmPlot(sprintf('Group%d', iGroup));
            iGroup = iGroup + 1;
        end
        % replot mean waveforms
        hFigWav = plotMeanWaveforms(hFigWav, hClust, hCfg, maxAmp);
    end

    info_ = jrclust.utils.info();
    hFigWav.axApply('default', @title, sprintf('%s v%s; press [H] for help (scale: %0.1f uV)', info_.program, jrclust.utils.version(), maxAmp));

    hFigWav = setFigWavXTicks(hFigWav, hClust, 1);
    hFigWav.figData.helpText = {'[Left-click] Select unit', ...
                                '[Right-click] Select secondary unit', ...
                                '[Pan] hold wheel and drag', ...
                                '[Zoom] mouse wheel', ...
                                '[X + wheel] X-zoom select', ...
                                '[Y + wheel] Y-zoom select', ...
                                '[SPACE] Select next most similar unit', ...
                                '[(shift) UP]: Increase amplitude scale', ...
                                '[(shift) DOWN]: Decrease amplitude scale', ...
                                '------------------', ...
                                '[H] Help', ...
                                '[S] Split unit', ...
                                '[W] Toggle spike traces', ...
                                '[M] Merge selected units', ...
                                '[D] Delete selected unit', ...
                                '[A] Resample spikes', ...
                                '[Z] Zoom in on selected unit', ...
                                '[R] Reset view', ...
                                '------------------', ...
                                '[P] PSTH display'};
end
