function hFigWav = doPlotFigWav(hFigWav, hClust, hCfg, maxAmp)
    %DOPLOTFIGWAV Plot the main view (FigWav)
    nSites = numel(hCfg.siteMap);

    if isempty(hFigWav.figData) % construct from scratch
        hFigWav.axes();
        hFigWav.axApply(@set, 'Position', [.05 .05 .9 .9], 'XLimMode', 'manual', 'YLimMode', 'manual');
        hFigWav.axApply(@xlabel, 'Cluster #');
        hFigWav.axApply(@ylabel, 'Site #');
        hFigWav.axApply(@grid, 'on');

        % hFigWav.figData.vcTitle = 'Scale: %0.1f uV; [H]elp; [Left/Right]:Select cluster; (Sft)[Up/Down]:scale; [M]erge; [S]plit auto; [D]elete; [A]:Resample spikes; [P]STH; [Z]oom; in[F]o; [Space]:Find similar [0]:Annotate Delete [1]:Annotate Signle [2]:Annotate Multi'; % TW
        % hFigWav.axApply(@title, sprintf('Scale: %0.1f uV; [H]elp; [Left/Right]:Select cluster; (Sft)[Up/Down]:scale; [M]erge; [S]plit auto; [D]elete; [A]:Resample spikes; [P]STH; [Z]oom; in[F]o; [Space]:Find similar [0]:Annotate Delete [1]:Annotate Signle [2]:Annotate Multi', maxAmp));
        
        hFigWav.axis([0, hClust.nClusters + 1, 0, nSites + 1]);
        hFigWav = plotSpikeWaveforms(hFigWav, hClust, hCfg, maxAmp);
        hFigWav = plotMeanWaveforms(hFigWav, hClust, hCfg, maxAmp);
        hFigWav.setHideOnDrag('hSpkAll');
        hFigWav.figData.isPlotted = true;
    else
        hFigWav = plotSpikeWaveforms(hFigWav, hClust, hCfg, maxAmp);
        % clear mean waveforms
        iGroup = 1;
        while hFigWav.hasPlot(sprintf('Group%d', iGroup))
            hFigWav.rmPlot(sprintf('Group%d', iGroup));
            iGroup = iGroup + 1;
        end
        % replot mean waveforms
        hFigWav = plotMeanWaveforms(hFigWav, hClust, hCfg, maxAmp);
    end

    info_ = jrclust.utils.info();
    hFigWav.axApply(@title, sprintf('%s v%s; press [H] for help (scale: %0.1f uV)', info_.program, jrclust.utils.version(), maxAmp));

    hFigWav = setFigWavXTicks(hFigWav, hClust, true);
    hFigWav.figData.helpText = {'[Left-click] Cluster select/unselect (point at blank)', ...
                                '[Right-click] Second cluster select (point at blank)', ...
                                '[Pan] hold wheel and drag', ...
                                '[Zoom] mouse wheel', ...
                                '[X + wheel] x-zoom select', ...
                                '[Y + wheel] y-zoom select', ...
                                '[SPACE] clear zoom', ...
                                '[(shift) UP]: increase amplitude scale', ...
                                '[(shift) DOWN]: decrease amplitude scale', ...
                                '------------------', ...
                                '[H] Help', ...
                                '[S] Split auto', ...
                                '[W] Spike waveforms (toggle)', ...
                                '[M] merge cluster', ...
                                '[D] delete cluster', ...
                                '[A] Resample spikes', ...
                                '[Z] zoom selected cluster', ...
                                '[R] reset view', ...
                                '------------------', ...
                                '[U] update all', ...
                                '[C] correlation plot', ...
                                '[T] show amp drift vs time', ...
                                '[J] projection view', ...
                                '[V] ISI return map', ...
                                '[I] ISI histogram', ...
                                '[E] Intensity map', ...
                                '[P] PSTH display', ...
                                '[O] Overlap average waveforms across sites'};
end
