%--------------------------------------------------------------------------
function fieldNames = structFieldsByDim(structName, dim)
    % a registry for the field names of structs, by dimension of their values

    if dim < 1 || dim > 3
        error('bad dimension: %d', dim);
    end

    fieldNamesS_clu = {
        {'clusterSites', ... % 1-dimensional fields
         'nSpikesPerCluster', ...
         'clusterXPositions', ...
         'clusterYPositions', ...
         'vrVmin_clu', ...
         'viSite_min_clu', ...
         'vrVpp_clu', ...
         'vrSnr_clu', ...
         'vnSite_clu', ...
         'vnSpk_clu', ...
         'vrIsoDist_clu', ...
         'vrLRatio_clu', ...
         'vrIsiRatio_clu', ...
         'vrVpp_uv_clu', ...
         'vrVmin_uv_clu', ...
         'clusterCenters', ...
         'spikeClusters', ...
         'spikeClustersAuto', ...
         'clusterNotes', ...
         'spikesByCluster'},
        {'mrWavCor'}, % 2-dimensional fields
        {'trWav_spk_clu', ... % 3-dimensional fields
         'tmrWav_spk_clu', ...
         'trWav_raw_clu', ...
         'tmrWav_raw_clu', ...
         'tmrWav_clu', ...
         'tmrWav_raw_lo_clu', ...
         'tmrWav_raw_hi_clu'}
    }

    switch structName
        case 'S_clu'
            fieldNames = fieldNamesS_clu{dim};

        otherwise
            error('not implemented yet');
    end
end
