function hFigWav = doPlotFigWav(hFigWav, hClust, hCfg)
    %DOPLOTFIGWAV
    % Show number of spikes per clusters
    % hold on; tight_plot(gca, [.04 .04], [.04 .02]);

    % hCfg.LineWidth = 1; %plot a thicker line
    % hCfg.viSite_clu = hClust.viSite_clu;
    nSites = numel(hCfg.siteMap);

    if isempty(hFigWav.figMetadata)
        % initialize
        hFigWav.figMetadata.maxAmp = hCfg.maxAmp;
        % hFigWav.figMetadata.hAx = hFigWav.axes();
        hFigWav.axes();
        % set(gca, 'Position', [.05 .05 .9 .9], 'XLimMode', 'manual', 'YLimMode', 'manual');
        hFigWav.axSet('Position', [.05 .05 .9 .9], 'XLimMode', 'manual', 'YLimMode', 'manual');
        %xlabel('Cluster #');    ylabel('Site #');   grid on;
        hFigWav.xlabel('Cluster #');
        hFigWav.ylabel('Site #');
        hFigWav.grid('on');

        % hFigWav.figMetadata.vcTitle = 'Scale: %0.1f uV; [H]elp; [Left/Right]:Select cluster; (Sft)[Up/Down]:scale; [M]erge; [S]plit auto; [D]elete; [A]:Resample spikes; [P]STH; [Z]oom; in[F]o; [Space]:Find similar [0]:Annotate Delete [1]:Annotate Signle [2]:Annotate Multi'; % TW
        % title_(sprintf(hFigWav.figMetadata.vcTitle, hFigWav.figMetadata.maxAmp)); %update scale
        hFigWav.title(sprintf('Scale: %0.1f uV; [H]elp; [Left/Right]:Select cluster; (Sft)[Up/Down]:scale; [M]erge; [S]plit auto; [D]elete; [A]:Resample spikes; [P]STH; [Z]oom; in[F]o; [Space]:Find similar [0]:Annotate Delete [1]:Annotate Signle [2]:Annotate Multi', hFigWav.figMetadata.maxAmp));

        % set(hFigWav, 'KeyPressFcn', @keyPressFcn_FigWav_, 'CloseRequestFcn', @exit_manual_, 'BusyAction', 'cancel');
        % axis_([0, hClust.nClusters + 1, 0, nSites + 1]);
        hFigWav.axis([0, hClust.nClusters + 1, 0, nSites + 1]);
        return; %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

        % add_menu_(hFigWav, hCfg);
        % mouse_figure(hFigWav, hFigWav.figMetadata.hAx, @button_CluWav_);
        hFigWav.figMetadata = plot_spkwav_(hFigWav.figMetadata, hFigWav); %plot spikes
        hFigWav.figMetadata = plot_tnWav_clu_(hFigWav.figMetadata, hCfg); %do this after plotSpk_
        hFigWav.figMetadata.cvhHide_mouse = mouse_hide_(hFigWav, hFigWav.figMetadata.hSpkAll, hFigWav.figMetadata);
    else
        %     mh_info = [];
        hFigWav.figMetadata = plot_spkwav_(hFigWav.figMetadata, hFigWav); %plot spikes
        try delete(hFigWav.figMetadata.vhPlot); catch; end %delete old text
        hFigWav.figMetadata = rmfield_(hFigWav.figMetadata, 'vhPlot');
        hFigWav.figMetadata = plot_tnWav_clu_(hFigWav.figMetadata, hCfg); %do this after plotSpk_
    end

    % create text
    % S0 = set0_(mh_info);
    fText = get_set_(hFigWav.figMetadata, 'fText', get_set_(hCfg, 'Text', 1));
    hFigWav.figMetadata = figWav_clu_count_(hFigWav.figMetadata, hClust, fText);
    hFigWav.figMetadata.csHelp = { ...
    '[Left-click] Cluter select/unselect (point at blank)', ...
    '[Right-click] Second cluster select (point at blank)', ...
    '[Pan] hold wheel and drag', ...
    '[Zoom] mouse wheel', ...
    '[X + wheel] x-zoom select', ...
    '[Y + wheel] y-zoom select', ...
    '[SPACE] clear zoom', ...
    '[(shift) UP]: increase amplitude scale', ...
    '[(shift) DOWN]: decrease amplitude scale', ...
    '------------------', ...
    '[H] Help', ...
    '[S] Split auto', ...
    '[W] Spike waveforms (toggle)', ...
    '[M] merge cluster', ...
    '[D] delete cluster', ...
    '[A] Resample spikes', ...
    '[Z] zoom selected cluster', ...
    '[R] reset view', ...
    '------------------', ...
    '[U] update all', ...
    '[C] correlation plot', ...
    '[T] show amp drift vs time', ...
    '[J] projection view', ...
    '[V] ISI return map', ...
    '[I] ISI histogram', ...
    '[E] Intensity map', ...
    '[P] PSTH display', ...
    '[O] Overlap average waveforms across sites', ...
    };
end
